In [1]:
from topsis import Topsis
import numpy as np
import pandas as pd

df = pd.read_excel("fiis.xlsx")
df.head()

fii                          segmento                    tipo_anbima  \
0  KNCR11                            Papéis  Títulos e Valores Mobiliários   
1  KNIP11                            Papéis  Títulos e Valores Mobiliários   
2  XPML11                         Shoppings                          Renda   
3  HGLG11  Imóveis Industriais e Logísticos                          Renda   
4  BTLG11  Imóveis Industriais e Logísticos                          Renda   

  valor_atual variacao_valor_atual dividend_yield valorização_12m   pvp  \
0       99,94               -0,16%          11,78           4,89%  0,99   
1       84,69               -0,59%          12,54          -5,20%  0,94   
2       97,97                0,03%          11,22         -12,62%  0,84   
3      148,34               -0,51%           8,88          -4,17%  0,91   
4       94,40                0,60%           9,85          -2,04%  0,92   

   caixa            cnpj_fii                              administrador  \
0  11,33  16.706.958/0001-32                          INTRAG DTVM LTDA.   
1   2,74  24.960.430/0001-13                          INTRAG DTVM LTDA.   
2   6,44  28.757.546/0001-00                XP INVESTIMENTOS CCTVM S.A.   
3   1,86  11.728.688/0001-47                 PLURAL S.A. BANCO MÚLTIPLO   
4  12,77  11.839.593/0001-09  BTG PACTUAL SERVIÇOS FINANCEIROS S/A DTVM   

   cnpj_administrador liquidez_diaria_media participação_ifix  
0  62.418.140/0001-31         12.911.084,24             7,070  
1  62.418.140/0001-31          8.268.229,10             5,405  
2  02.332.886/0001-04         12.103.085,48             4,292  
3  45.246.410/0001-55          6.367.508,38             3,991  
4  59.281.253/0001-23          8.045.519,86             3,215

In [2]:
df_tratado = df[['dividend_yield', 'valor_atual', 'pvp', 'caixa']].apply(lambda x: x.str.replace(',','.').astype("float"))
df_tratado['dividend_yield'] = df_tratado['dividend_yield']/100
evaluation_matrix = df_tratado.values
evaluation_matrix

array([[1.1780e-01, 9.9940e+01, 9.9000e-01, 1.1330e+01],
       [1.2540e-01, 8.4690e+01, 9.4000e-01, 2.7400e+00],
       [1.1220e-01, 9.7970e+01, 8.4000e-01, 6.4400e+00],
       [8.8800e-02, 1.4834e+02, 9.1000e-01, 1.8600e+00],
       [9.8500e-02, 9.4400e+01, 9.2000e-01, 1.2770e+01],
       [1.2900e-01, 9.0000e+00, 1.0000e+00, 2.1900e+00],
       [9.1400e-02, 1.3155e+02, 8.2000e-01, 2.8600e+00],
       [1.0650e-01, 1.1077e+02, 8.8000e-01, 1.6700e+00],
       [1.1090e-01, 9.5150e+01, 7.6000e-01, 7.6100e+00],
       [1.4180e-01, 9.2940e+01, 9.5000e-01, 2.6000e+00],
       [1.0280e-01, 9.1110e+01, 8.2000e-01, 6.7100e+00],
       [1.1390e-01, 1.7517e+02, 8.1000e-01, 3.4900e+00],
       [1.3540e-01, 6.3300e+01, 7.9000e-01, 3.5300e+00],
       [1.4180e-01, 6.4000e+00, 7.5000e-01, 3.2000e+00],
       [1.2840e-01, 9.8080e+01, 9.7000e-01, 3.0500e+00],
       [1.9190e-01, 7.5850e+01, 6.6000e-01, 1.0100e+00],
       [1.0080e-01, 7.1990e+01, 7.0000e-01, 1.0100e+00],
       [1.5560e-01, 7.1280e+01,

### CRITÉRIOS

'dividend_yield' - 40%
'valor_atual' - 20%
'pvp' - 30%
'caixa' - 10%

In [3]:
weights = [0.4, 0.2, 0.3, 0.1]
# weights = [5, 5, 9, 0]
'''
if higher value is preferred - True
if lower value is preferred - False
'''
criterias = np.array([True, True, True, True])

t = Topsis(evaluation_matrix, weights, criterias)

t.calc()

print("best_distance\t", t.best_distance)
print("worst_distance\t", t.worst_distance)

# print("weighted_normalized",t.weighted_normalized)

print("worst_similarity\t", t.worst_similarity)
print("rank_to_worst_similarity\t", t.rank_to_worst_similarity())

print("best_similarity\t", t.best_similarity)
print("rank_to_best_similarity\t", t.rank_to_best_similarity())


Step 1
 [[1.1780e-01 9.9940e+01 9.9000e-01 1.1330e+01]
 [1.2540e-01 8.4690e+01 9.4000e-01 2.7400e+00]
 [1.1220e-01 9.7970e+01 8.4000e-01 6.4400e+00]
 [8.8800e-02 1.4834e+02 9.1000e-01 1.8600e+00]
 [9.8500e-02 9.4400e+01 9.2000e-01 1.2770e+01]
 [1.2900e-01 9.0000e+00 1.0000e+00 2.1900e+00]
 [9.1400e-02 1.3155e+02 8.2000e-01 2.8600e+00]
 [1.0650e-01 1.1077e+02 8.8000e-01 1.6700e+00]
 [1.1090e-01 9.5150e+01 7.6000e-01 7.6100e+00]
 [1.4180e-01 9.2940e+01 9.5000e-01 2.6000e+00]
 [1.0280e-01 9.1110e+01 8.2000e-01 6.7100e+00]
 [1.1390e-01 1.7517e+02 8.1000e-01 3.4900e+00]
 [1.3540e-01 6.3300e+01 7.9000e-01 3.5300e+00]
 [1.4180e-01 6.4000e+00 7.5000e-01 3.2000e+00]
 [1.2840e-01 9.8080e+01 9.7000e-01 3.0500e+00]
 [1.9190e-01 7.5850e+01 6.6000e-01 1.0100e+00]
 [1.0080e-01 7.1990e+01 7.0000e-01 1.0100e+00]
 [1.5560e-01 7.1280e+01 8.0000e-01 2.3400e+00]
 [8.7800e-02 7.2800e+00 8.3000e-01 6.7300e+00]
 [1.0950e-01 9.4780e+01 8.0000e-01 8.9500e+00]]

Step 2
 [[0.21583401 0.23379562 0.25979689 0.44562